### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by bartek18887** [rgtexa/Automaton#38]
My game crashes on startup.

Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 11/8/19 7:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Furnus (furnus)
Caused by: java.lang.RuntimeException: Invalid pulvus Recipes: simpleoregen:nethercertusquartzore
	at mrriegel.furnus.util.CrushRecipe.string2Stacks(CrushRecipe.java:59)
	at mrriegel.furnus.util.CrushRecipe.register(CrushRecipe.java:34)
	at mrriegel.furnus.proxy.CommonProxy.postInit(CommonProxy.java:34)
	at mrriegel.furnus.proxy.ClientProxy.postInit(ClientProxy.java:25)
	at mrriegel.furnus.Furnus.postInit(Furnus.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 886625464 bytes (845 MB) / 1909456896 bytes (1821 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -Xmx3072m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJ | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJ | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                     | None                                     |
	| LCHIJ | elucore              | 1.0                      | minecraft.jar                                     | None                                     |
	| LCHIJ | movillages           | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                        | None                                     |
	| LCHIJ | appliedenergistics2  | rv6-stable-3             | appliedenergistics2-rv6-stable-3.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJ | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| LCHIJ | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| LCHIJ | aroma1997core        | 2.0.0.0                  | Aroma1997Core-1.12.2-2.0.0.0.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJ | aroma1997sdimension  | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| LCHIJ | aromabackup          | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJ | aromabackuprecovery  | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJ | quark                | r1.5-130                 | Quark-r1.5-130.jar                                | None                                     |
	| LCHIJ | autoreglib           | 1.3-20                   | AutoRegLib-1.3-20.jar                             | None                                     |
	| LCHIJ | crafttweaker         | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| LCHIJ | mtlib                | 3.0.5                    | MTLib-3.0.5.jar                                   | None                                     |
	| LCHIJ | modtweaker           | 4.0.15                   | modtweaker-4.0.15.jar                             | None                                     |
	| LCHIJ | jei                  | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                         | None                                     |
	| LCHIJ | base                 | 3.10.0                   | base-1.12.2-3.10.0.jar                            | None                                     |
	| LCHIJ | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| LCHIJ | betterquesting       | 3.5.271                  | BetterQuesting-3.5.271.jar                        | None                                     |
	| LCHIJ | bqt                  | 1.0                      | BetterQuestingTriggerer-1.0.jar                   | None                                     |
	| LCHIJ | blockcraftery        | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
	| LCHIJ | ceramics             | 1.12-1.3.4               | Ceramics-1.12-1.3.4.jar                           | None                                     |
	| LCHIJ | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJ | ctm                  | MC1.12.2-0.3.2.20        | CTM-MC1.12.2-0.3.2.20.jar                         | None                                     |
	| LCHIJ | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJ | chiselsandbits       | 14.26                    | chiselsandbits-14.26.jar                          | None                                     |
	| LCHIJ | clumps               | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
	| LCHIJ | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | colytra              | 1.1.0                    | colytra-1.12.2-1.1.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJ | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| LCHIJ | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| LCHIJ | custommainmenu       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                 | None                                     |
	| LCHIJ | diethopper           | 1.1                      | diethopper-1.1.jar                                | None                                     |
	| LCHIJ | enderstorage         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | reborncore           | 3.16.4.478               | RebornCore-1.12.2-3.16.4.478-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJ | engineersworkshop    | 1.0.8.37                 | EngineersWorkshopReborn-1.12.2-1.0.8.37.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJ | valkyrielib          | 1.12.2-2.0.17.2          | valkyrielib-1.12.2-2.0.17.3.jar                   | None                                     |
	| LCHIJ | environmentaltech    | 1.12.2-2.0.17.1          | environmentaltech-1.12.2-2.0.17.1.jar             | None                                     |
	| LCHIJ | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | mekanism             | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                    | None                                     |
	| LCHIJ | theoneprobe          | 1.4.25                   | theoneprobe-1.12-1.4.25.jar                       | None                                     |
	| LCHIJ | immersiveengineering | 0.12-86                  | ImmersiveEngineering-0.12-86.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJ | exchangers           | 1.12.2-2.8               | Exchangers-1.12.2-2.8.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJ | extracells           | 2.6.1                    | ExtraCells-1.12.2-2.6.1a.jar                      | None                                     |
	| LCHIJ | limelib              | 1.7.12                   | limelib-1.12.2-1.7.12.jar                         | None                                     |
	| LCHIE | furnus               | 2.1.8                    | furnus-1.12.2-2.1.8.jar                           | None                                     |
	| LCHI  | guideapi             | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                       | None                                     |
	| LCHI  | harvest              | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                         | None                                     |
	| LCHI  | igwmod               | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar             | None                                     |
	| LCHI  | immersivecables      | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
	| LCHI  | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| LCHI  | immersivetech        | 1.3.10                   | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| LCHI  | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | ironchest            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| LCHI  | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| LCHI  | loottweaker          | 0.0.8                    | LootTweaker-1.12.2-0.0.8.jar                      | None                                     |
	| LCHI  | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| LCHI  | kc                   | 1.12                     | knobcontrol-1.12-4.0.20.jar                       | None                                     |
	| LCHI  | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
	| LCHI  | mantle               | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                          | None                                     |
	| LCHI  | mekanismgenerators   | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar          | None                                     |
	| LCHI  | mekanismtools        | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar               | None                                     |
	| LCHI  | morpheus             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| LCHI  | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
	| LCHI  | oreexcavation        | 1.4.129                  | OreExcavation-1.4.129.jar                         | None                                     |
	| LCHI  | p455w0rdslib         | 2.0.35                   | p455w0rdslib-1.12-2.0.35.jar                      | None                                     |
	| LCHI  | shetiphiancore       | 3.5.8                    | shetiphiancore-1.12.0-3.5.8.jar                   | None                                     |
	| LCHI  | platforms            | 1.4.6                    | platforms-1.12.0-1.4.6.jar                        | None                                     |
	| LCHI  | reccomplex           | 1.4.7                    | RecurrentComplex-1.4.7.jar                        | None                                     |
	| LCHI  | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCHI  | bq_standard          | 3.4.145                  | StandardExpansion-3.4.145.jar                     | None                                     |
	| LCHI  | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
	| LCHI  | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                   | None                                     |
	| LCHI  | tp                   | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar        | None                                     |
	| LCHI  | usefulnullifiers     | 1.5.0                    | usefulnullifiers-1.5.0.jar                        | None                                     |
	| LCHI  | universalmodifiers   | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.17.3.jar                   | None                                     |
	| LCHI  | vc                   | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                       | None                                     |
	| LCHI  | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| LCHI  | wearablebackpacks    | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
	| LCHI  | weirdinggadget       | 1.0                      | weirdinggadget-1.12.2-2.0.5-universal.jar         | None                                     |
	| LCHI  | wct                  | 3.9.68                   | WirelessCraftingTerminal-1.12.2-3.9.68.jar        | None                                     |
	| LCHI  | woot                 | 1.12.2-1.4.6             | woot-1.12.2-1.4.6.jar                             | None                                     |
	| LCHI  | xtones               | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                          | None                                     |
	| LCHI  | elulib               | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  c4.colytra.asm.ElytraTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce GT 740M/PCIe/SSE2'
	AE2 Version: stable rv6-stable-3 for Forge 14.23.5.2768
	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-3.jar
		* Base|API (1.0.0) from base-1.12.2-3.10.0.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.68.jar
		* BetterQuesting|API (3.1) from BetterQuesting-3.5.271.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.271.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.5-130.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselsAndBitsAPI (14.25.0) from chiselsandbits-14.26.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.6-61.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-86.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-86.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.12.1.217.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.35.jar
		* QuarkAPI (2) from Quark-r1.5-130.jar
		* reborncoreAPI (3.16.4.478) from RebornCore-1.12.2-3.16.4.478-universal.jar
		* reborncoreAPI|Power (3.16.4.478) from RebornCore-1.12.2-3.16.4.478-universal.jar
		* reborncoreAPI|Praescriptum (3.16.4.478) from RebornCore-1.12.2-3.16.4.478-universal.jar
		* reborncoreAPI|Recipe (3.16.4.478) from RebornCore-1.12.2-3.16.4.478-universal.jar
		* reborncoreAPI|Tile (3.16.4.478) from RebornCore-1.12.2-3.16.4.478-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.25.jar
		* valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.17.3.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.68.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.4.478
		Runtime Debofucsation 1
		RenderEngine: 0
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON

**Comment by StephJ2Fan** [comment]
Would consider bumping up ram to at least 6 GB. You only have 3 GB allocated.
